###############################################################################
# Jekyll Configuration
highlighter: rouge
markdown: kramdown
permalink: /:title.html
#paginate: 5
port: 3000
safe: true
language: 'en-uk'
plugins: [jekyll-feed]

###############################################################################
# Page Personal Details
url: http://luizfcp.github.io/
baseurl: /
author: Luiz Fernando Coelho Passos
title: Luiz Fernando Coelho Passos
description: Personal Landing Page
avatar: .jpg

# Contacts
email: luizfcpassos@gmail.com

# Upon Request for Phone, Skype, Hangouts, etc.
urequest: Upon request

# Social Usernames for Twitter, Github, Medium, Linkedin
username: luizfcp

# Research Outputs
google_scholar: BrDL99cAAAAJ
orcid: 0000-0001-8728-9449

# Google Analytics
google_analytics: UA-47728743-1
